# Generated by Django 4.0.1 on 2022-01-28 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('service', models.CharField(max_length=300, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('password', models.CharField(default='', max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwManager.user')),
            ],
        ),
    ]
