# Generated by Django 4.0.1 on 2022-01-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwManager', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pwManager.user'),
        ),
    ]
